// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Kalau DATABASE_URL kosong, dia pakai string dummy biar nggak error pas build
    url: process.env["DATABASE_URL"]!,
  },
});